title: ICLR2025
description: "ICLR 2025 Machine Learning for Remote Sensing Workshop"
baseurl: "/iclr2025"
url: "https://ml-for-rs.github.io/ml-for-remote-sensing"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 


